- name : Download lastest and build docker
  hosts: docker
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: download
    shell: 'curl -u admin:Hanoi@180417 -L "http://192.168.0.6:8081/service/rest/v1/search/assets/download?sort=version&repository=PythonDeploy" -H "accept: application/json" --output /home/ansibleadmin/main.zip'
    args:
      chdir: /home/ansibleadmin
  - name: unzip
    shell: 'unzip -o main.zip'
  - name: create docker file
    copy:
      dest: /home/ansibleadmin/Dockerfile
      content: |
        FROM python
        WORKDIR /app
        COPY ./main.py main.py
        RUN pip3 install Flask
        CMD ["python3", "/app/main.py"]
  - name: build
    docker_image:
      name: pythondocker
      source: build
      build:
       path: /home/ansibleadmin
       pull: yes
      force_tag: yes
      state: present
  - name: run
    docker_container:
      name: pythondocker_container
      image: pythondocker
      state: started
      recreate: yes
      published_ports:
      - 0.0.0.0:5000:5000
